# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param simulator.modelsimInstallPath C:/modeltech_pe_10.4c/win32pe
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/vivado/top/top.cache/wt [current_project]
set_property parent.project_path F:/vivado/top/top.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files c:/Users/Sevenenen/Desktop/god.coe
add_files c:/Users/Sevenenen/Desktop/test.coe
read_ip -quiet F:/vivado/top/top.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all f:/vivado/top/top.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/vivado/top/top.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all f:/vivado/top/top.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]
set_property is_locked true [get_files F:/vivado/top/top.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci]

read_ip -quiet F:/vivado/top/top.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all f:/vivado/top/top.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0_ooc.xdc]
set_property is_locked true [get_files F:/vivado/top/top.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0.xci]

read_verilog -library xil_defaultlib {
  F:/vivado/top/top.srcs/sources_1/new/getpic_ready.v
  F:/vivado/top/top.srcs/sources_1/new/vga_pos.v
  F:/vivado/top/top.srcs/sources_1/new/sccb_solve.v
  F:/vivado/top/top.srcs/sources_1/new/reg_solve.v
  F:/vivado/top/top.srcs/sources_1/new/vga_show.v
  F:/vivado/top/top.srcs/sources_1/new/getpic.v
  F:/vivado/top/top.srcs/sources_1/new/display7.v
  F:/vivado/top/top.srcs/sources_1/new/bluetooth.v
  F:/vivado/top/top.srcs/sources_1/new/camera.v
  F:/vivado/top/top.srcs/sources_1/new/top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/vivado/top/top.srcs/constrs_1/new/top.xdc
set_property used_in_implementation false [get_files F:/vivado/top/top.srcs/constrs_1/new/top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
