set_property PACKAGE_PIN  J15  [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]

set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property PACKAGE_PIN  B12  [get_ports row_vga]
set_property IOSTANDARD LVCMOS33 [get_ports row_vga]

set_property PACKAGE_PIN  B11  [get_ports col_vga]
set_property IOSTANDARD LVCMOS33 [get_ports col_vga]

set_property PACKAGE_PIN  A3   [get_ports {red_vga[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red_vga[0]}]
set_property PACKAGE_PIN    B4 [get_ports {red_vga[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red_vga[1]}]
set_property PACKAGE_PIN   C5  [get_ports {red_vga[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red_vga[2]}]
set_property PACKAGE_PIN   A4  [get_ports {red_vga[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red_vga[3]}]

set_property PACKAGE_PIN  C6   [get_ports {green_vga[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green_vga[0]}]
set_property PACKAGE_PIN   A5  [get_ports {green_vga[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green_vga[1]}]
set_property PACKAGE_PIN   B6  [get_ports {green_vga[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green_vga[2]}]
set_property PACKAGE_PIN   A6  [get_ports {green_vga[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green_vga[3]}]

set_property PACKAGE_PIN   B7  [get_ports {blue_vga[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue_vga[0]}]
set_property PACKAGE_PIN   C7  [get_ports {blue_vga[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue_vga[1]}]
set_property PACKAGE_PIN   D7  [get_ports {blue_vga[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue_vga[2]}]
set_property PACKAGE_PIN   D8  [get_ports {blue_vga[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue_vga[3]}]

set_property PACKAGE_PIN   C17  [get_ports pwdn]
set_property IOSTANDARD LVCMOS33 [get_ports pwdn]

set_property PACKAGE_PIN   D17  [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

set_property PACKAGE_PIN   D18  [get_ports camera_data[0]]
set_property IOSTANDARD LVCMOS33 [get_ports camera_data[0]]
set_property PACKAGE_PIN   E17  [get_ports camera_data[1]]
set_property IOSTANDARD LVCMOS33 [get_ports camera_data[1]]
set_property PACKAGE_PIN   E18  [get_ports camera_data[2]]
set_property IOSTANDARD LVCMOS33 [get_ports camera_data[2]]
set_property PACKAGE_PIN   F18  [get_ports camera_data[3]]
set_property IOSTANDARD LVCMOS33 [get_ports camera_data[3]]
set_property PACKAGE_PIN   G17  [get_ports camera_data[4]]
set_property IOSTANDARD LVCMOS33 [get_ports camera_data[4]]
set_property PACKAGE_PIN   G18  [get_ports camera_data[5]]
set_property IOSTANDARD LVCMOS33 [get_ports camera_data[5]]
set_property PACKAGE_PIN   D14  [get_ports camera_data[6]]
set_property IOSTANDARD LVCMOS33 [get_ports camera_data[6]]  
set_property PACKAGE_PIN   E16  [get_ports camera_data[7]]
set_property IOSTANDARD LVCMOS33 [get_ports camera_data[7]]

set_property PACKAGE_PIN   F16  [get_ports xclk]
set_property IOSTANDARD LVCMOS33 [get_ports xclk]

set_property PACKAGE_PIN   G16  [get_ports href]
set_property IOSTANDARD LVCMOS33 [get_ports href]

set_property PACKAGE_PIN   H14  [get_ports sio_d]
set_property IOSTANDARD LVCMOS33 [get_ports sio_d]

set_property PULLUP TRUE [get_ports sio_d]

set_property PACKAGE_PIN   F13  [get_ports pclk]
set_property IOSTANDARD LVCMOS33 [get_ports pclk]

set_property PACKAGE_PIN   G13  [get_ports vsync]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]

set_property PACKAGE_PIN   H16  [get_ports sio_c]
set_property IOSTANDARD LVCMOS33 [get_ports sio_c]

set_property PACKAGE_PIN   G6  [get_ports bluetooth_in]
set_property IOSTANDARD LVCMOS33 [get_ports bluetooth_in]

set_property PACKAGE_PIN   T10  [get_ports display[0]]
set_property IOSTANDARD LVCMOS33 [get_ports display[0]]
set_property PACKAGE_PIN   R10  [get_ports display[1]]
set_property IOSTANDARD LVCMOS33 [get_ports display[1]]
set_property PACKAGE_PIN   K16  [get_ports display[2]]
set_property IOSTANDARD LVCMOS33 [get_ports display[2]]
set_property PACKAGE_PIN   K13  [get_ports display[3]]
set_property IOSTANDARD LVCMOS33 [get_ports display[3]]
set_property PACKAGE_PIN   P15  [get_ports display[4]]
set_property IOSTANDARD LVCMOS33 [get_ports display[4]]
set_property PACKAGE_PIN   T11  [get_ports display[5]]
set_property IOSTANDARD LVCMOS33 [get_ports display[5]]
set_property PACKAGE_PIN   L18  [get_ports display[6]]
set_property IOSTANDARD LVCMOS33 [get_ports display[6]]

set_property PACKAGE_PIN   J17  [get_ports dis_pos[0]]
set_property IOSTANDARD LVCMOS33 [get_ports dis_pos[0]]
set_property PACKAGE_PIN   J18  [get_ports dis_pos[1]]
set_property IOSTANDARD LVCMOS33 [get_ports dis_pos[1]]
set_property PACKAGE_PIN   T9  [get_ports dis_pos[2]]
set_property IOSTANDARD LVCMOS33 [get_ports dis_pos[2]]
set_property PACKAGE_PIN   J14  [get_ports dis_pos[3]]
set_property IOSTANDARD LVCMOS33 [get_ports dis_pos[3]]
set_property PACKAGE_PIN   P14  [get_ports dis_pos[4]]
set_property IOSTANDARD LVCMOS33 [get_ports dis_pos[4]]
set_property PACKAGE_PIN   T14  [get_ports dis_pos[5]]
set_property IOSTANDARD LVCMOS33 [get_ports dis_pos[5]]
set_property PACKAGE_PIN   K2  [get_ports dis_pos[6]]
set_property IOSTANDARD LVCMOS33 [get_ports dis_pos[6]]
set_property PACKAGE_PIN   U13  [get_ports dis_pos[7]]
set_property IOSTANDARD LVCMOS33 [get_ports dis_pos[7]]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets pclk] 